### ISSUE TITLE
Extension and UIAppearance

### ISSUE THREAD

**Issue by rosskimes** [AgileBits/onepassword-app-extension#205]
Our app has a dark color theme and we use `UIAppearance` to set it up. It seems that some of those appearance calls get carried over to the 1Password extension. The navigation bar uses my app's dark theme, but the status bar changes to black (it is white while in the app).

Ideally it would retain 1Password's color scheme, but even using our scheme with a correct status bar color would be acceptable.

Any ideas?

![img_3560](https://cloud.githubusercontent.com/assets/302299/7456524/b1178b2e-f24a-11e4-8772-90f98577a2d6.PNG)

**Comment by radazzouz** [comment]
Hi @rosskimes,

Thanks for taking the time to write in :+1:

The 1Password extension respects the appearance of your view controller navigation bar, but does not respect the `preferredStatusBarStyle` of your view controller. I am pretty sure that you are experiencing on of these following rdars:

* [rdar://17916449](http://openradar.appspot.com/radar?id=6397505050771456).
* [rdar://18273339](rdar://18273339) - See the *Status Bar Style* section here: http://www.atomicbird.com/blog/ios-app-extension-tips

However, there might be a workaround: You could force the 1Password extension to _”ignore”_ your app’s dark theme. To do so you need to call

```objective-c
[[UINavigationBar appearance] setBarTintColor:nil];
[[UINavigationBar appearance] setTintColor:nil];

```
in your view controller. Note that this will affect your view controller’s navigation bar appearance too, so you may need to set the tint colors back to their original values. Hope that this will help you :-)

Since this is not an App Extension API issue, I am closing this issue for now.

Thanks!

**Comment by rosskimes** [comment]
Thanks! I fixed it by just not using UIAppearance. I only create a couple of navigation controllers, so it was not that bad to manually set their properties until the bug fix hits.

**Comment by radazzouz** [comment]
Thanks for getting back to us and for letting us know that you've sorted it all out! Thats great news indeed!

If there's anything else I can do to help, please do not hesitate to ask :smile: 

Cheers!

**Comment by peterstuart** [comment]
@radazzouz I filed a bug on this issue with Apple (saying that extensions should not inherit appearance proxies from host apps), and got this reply:

> The extension explicitly has to opt out using the NSExtensionOverridesHostUIAppearance key. As long as extensions do not adopt this key, the behavior will not have changed.
>
> Thank you for your feedback. Engineering has determined that this issue behaves as intended.

I can't find any documentation about the `NSExtensionOverridesHostUIAppearance` key—maybe introduced in iOS 10?

**Comment by radazzouz** [comment]
Thanks so much for taking the time to share this info with us, @peterstuart! We really appreciate it.

That said, I must admit that I never knew that `NSExtensionOverridesHostUIAppearance` even existed and I partly blame the lack of documentation. 

Anyway, I may have an idea or two about how to handle `NSExtensionOverridesHostUIAppearance`. 😉

I just reopened this issue and I will post my findings as soon as I know more about it.

Cheers!

**Comment by manicaesar** [comment]
Hi, any update on this? Google still does not know anything about `NSExtensionOverridesHostUIAppearance` :(

**Comment by MrAlek** [comment]
I can confirm it works in iOS 10 putting it into the `NSExtension` dictionary! Haven't yet in iOS 9

**Comment by gks** [comment]
Hi all.

We have not yet looked into this yet. I'll have to see if I can take a look soon but I have nothing to add yet I'm afraid. 

Do you folks know of anywhere this is documented?

**Comment by peterstuart** [comment]
It is completely undocumented as far as I can tell. 😕

**Comment by gks** [comment]
Brilliant! Alright. That does make this more difficult but I'll see what I can do. I don't know where this fits into my schedule at the moment yet, so don't hold your breath but I am aware it needs to be looked into more now :)

**Comment by gks** [comment]
Hi folks,

We have this implemented in the latest 1Password for iOS beta. If any of you who have reported this would like to do some testing I'd be happy to get you into the beta. You can shoot me an email at support+appex at agilebits dot com. Be sure to mention your github name in the email and a link to this post. I, or someone else (whoever gets to it first), will get you added. Just report back here any successes or failures you have.

**Comment by gks** [comment]
And this was released officially in 1Password 6.5.3.

**Comment by gks** [comment]
@peterstuart great to hear! You got a [mention in the release notes](https://app-updates.agilebits.com/product_history/OPI4#v653002) for your help in this. So, thank you for your help!
